language: php
php:
  - 5.4
  - 5.5

env:
  global:
  matrix:
    - REQUIRE=no-dev

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer --${REQUIRE} --prefer-source install

services: mongodb
